"""Render presentation figures from checked pilot graphs; never overwrite receipts.

One fixed layout across all pilots makes shape changes comparable. Neutral node
colors do not imply demographic categories. PNGs are derivatives, not new runs.
"""
import json
import shutil

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import networkx as nx

from export_research_viewer import ROOT, pilot_records, sha256, inspect_png


def render():
    records = pilot_records(ROOT)
    graphs = {r['run_id']: nx.read_adjlist(ROOT / r['source']) for r in records}
    if not graphs:
        raise ValueError('No verified pilot graphs.')
    union = nx.compose_all(list(graphs.values()))
    # Shared identity coordinates are a display convention, not social distance.
    layout = nx.spring_layout(union, seed=12, k=.7, iterations=400)
    destination = ROOT / 'outputs/presentation'
    public = ROOT / 'viewer/public/data/presentation'
    destination.mkdir(parents=True, exist_ok=True)
    public.mkdir(parents=True, exist_ok=True)
    manifest = dict(status='PRESENTATION_DERIVATIVES_NOT_NEW_EXPERIMENTS',
                    layout='shared union spring layout, seed 12; no geographic meaning',
                    api_calls=0, runs={})
    for run in records:
        graph = graphs[run['run_id']]
        # Manuscript panel only. Methods, caveats and numerical results belong in
        # the accompanying caption, never embedded as a presentation slide.
        fig = plt.figure(figsize=(7, 6), facecolor='white')
        ax = fig.add_axes([.015, .015, .97, .97])
        ax.set_facecolor('white')
        nx.draw_networkx_edges(graph, layout, ax=ax, edge_color='#59615d', alpha=.45, width=.65)
        nx.draw_networkx_nodes(graph, layout, ax=ax, node_color='white', edgecolors='#202925',
                               node_size=120, linewidths=.8)
        nx.draw_networkx_labels(graph, layout, ax=ax, font_size=6.5, font_color='#17221c')
        ax.set_xlim(-1.12, 1.12)
        ax.set_ylim(-1.12, 1.12)
        ax.set_aspect('equal')
        ax.axis('off')
        png = destination / (run['run_id'] + '.png')
        svg = png.with_suffix('.svg')
        fig.savefig(png, dpi=400, facecolor='white')
        fig.savefig(svg, facecolor='white')
        plt.close(fig)
        caption = (f'Network generated by {run["model"]} using {run["method"]}; '
                   f'country framing {run["culture"]}, instruction language {run["language"]}, seed {run["seed"]}. '
                   f'{len(graph)} personas and {graph.number_of_edges()} undirected ties. '
                   'Node labels identify synthetic personas. All pilot panels use identical node coordinates from a shared union layout; '
                   'positions do not represent geography or observed social distance. '
                   'Exploratory engineering pilot with a US-structured roster including minors; not validated human behavior.')
        png.with_suffix('.caption.md').write_text(caption + '\n', encoding='utf-8')
        if not inspect_png(png) or sha256(ROOT / run['source']) != run['source_sha256']:
            raise ValueError('Presentation rendering failed or source changed.')
        shutil.copyfile(png, public / png.name)
        shutil.copyfile(svg, public / svg.name)
        manifest['runs'][run['run_id']] = dict(source=run['source'], source_sha256=run['source_sha256'],
            png_url=f'./data/presentation/{png.name}', png_sha256=sha256(png),
            svg_url=f'./data/presentation/{svg.name}', svg_sha256=sha256(svg), caption=caption,
            nodes=sorted(graph.nodes()), edges=sorted(sorted(edge) for edge in graph.edges()))
    encoded = json.dumps(manifest, indent=2)
    (destination / 'manifest.json').write_text(encoded, encoding='utf-8')
    (ROOT / 'viewer/public/data/presentation.json').write_text(encoded, encoding='utf-8')
    print(f'Rendered and decoded {len(records)} pilot figures. Original graph/PNG receipts unchanged. API calls: 0.')


if __name__ == '__main__':
    render()
