from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "speaker_notes"
PDF = OUT / "cross_cultural_linguistic_agentic_graph_speaker_notes.pdf"
TXT = OUT / "cross_cultural_linguistic_agentic_graph_speaker_notes.txt"


NOTES = r"""
# Project Title
Cross-Cultural and Linguistic Agentic Graph Simulation Framework

My project is about using large language models to generate social networks from synthetic people. In simple words, I give the model a group of 50 artificial people, each with demographic details and interests, and then I ask the model to decide who would likely be friends with whom.

Each dot in the network is one persona. Each line is a friendship connection generated by the model.

The title has three important parts:
- Cross-cultural means I tested different cultural settings like the US, India, Japan, and Brazil.
- Linguistic means I tested different prompt languages like English, Spanish, Hindi, and Japanese.
- Agentic graph simulation means the LLM acts like an agent that reasons over people and creates a graph of relationships.

# Main Hook
The big question is: if an AI model is asked to imagine a society, what kind of social structure does it create?

It is not only generating names or descriptions. It is generating relationships. That is why this matters. A model might say two people are likely to be friends because they share politics, religion, age group, community interests, or cultural background. So the network becomes a way to study the model's social assumptions.

# Earlier Research
This project builds on an earlier research repository called "LLMs generate structurally realistic social networks but overestimate political homophily."

That earlier work asked: can LLMs generate social networks that look realistic compared to real social networks?

They used older/base models such as:
- gpt-3.5-turbo
- gpt-4o
- llama3.1-8b
- llama3.1-70b
- gemma2-9b
- gemma2-27b

Their main goal was to check whether model-generated networks had realistic structure. They looked at things like how connected the network is, how clustered it is, and whether similar people connect with each other.

One major finding from that earlier work was that LLMs can create structurally believable social networks, but they often overestimate political homophily.

Homophily means similar people connecting with similar people. For example, if people with the same political affiliation mostly connect to each other, that is political homophily. If people of the same religion connect more often, that is religion homophily.

So the earlier paper gave the foundation: LLMs can generate social networks, but the generated networks may contain biases or exaggerated social patterns.

# What My Project Adds
My project extends that earlier work in a new direction. I did not only ask whether LLMs can generate networks. I asked what changes those networks.

I tested whether the generated social network changes when I change:
- the model
- the cultural context
- the prompt language
- the generation method

For newer models, I used:
- gpt-4.1
- gpt-4.1-mini
- gpt-4.1-nano

For cultural context, I used:
- United States
- India
- Japan
- Brazil

For prompt language, I used:
- English
- Spanish
- Hindi
- Japanese

For generation methods, I used:
- global
- local
- sequential
- iterative

The key idea is that the same 50 people can produce different networks depending on how the model is prompted.

# Dataset
The project uses one fixed roster of 50 synthetic personas.

Each persona has demographic details:
- gender
- age
- race or ethnicity
- religion
- political affiliation
- interests

For example, one persona might be a 31-year-old Democrat with interests in social justice, basketball, volunteering, craft beer, and live music. Another might be a 53-year-old Republican interested in hunting, fishing, church activities, classic rock, and conservative politics.

The important part is that I used the same 50 personas across experiments. That makes the experiment controlled. If the network changes, the people did not change. The model setting changed.

# Methodology
The methodology is simple but powerful.

First, I create or load the 50-person roster.

Second, I give those personas to the language model.

Third, the model chooses friendships between people.

Fourth, the friendships are saved as an adjacency list. That means for each person, the file records which other people they are connected to.

Fifth, I convert that into a graph.

In the graph:
- nodes are people
- edges are friendship ties
- groups are clusters of people who are more connected to each other
- bridges are connections between different groups

Then I analyze the graph using network science metrics.

# Four Generation Methods
The global method asks the model to generate the whole network at once. This gives the model a broad view, but it often creates sparser networks.

The local method focuses more on one person and their likely friends. It is more person-centered.

The sequential method builds the network step by step, going through the roster person by person.

The iterative method lets the network form through repeated refinement. This usually creates denser networks.

These methods matter because the way we ask the model to generate the network changes the final graph.

# Metrics Explained
Density means how many friendship connections exist compared to how many could possibly exist. A dense network has many lines. A sparse network has fewer lines.

Clustering means whether friends of a person are also friends with each other. High clustering means friend groups or communities are forming.

Largest connected component means the biggest part of the graph where everyone is connected by some path. If this is high, most people are part of one big social structure.

Modularity means how strongly the network separates into groups. Higher modularity means clearer communities.

Homophily means similarity-based connection. I measured whether people connect more often when they share gender, age, race or ethnicity, religion, or political affiliation.

Edge distance compares two generated networks. If edge distance is low, two models produced similar friendship patterns. If edge distance is high, they produced different networks.

# Research Question 1
When language is held constant, does changing cultural context alter homophily and network topology?

My answer is yes.

I kept the language fixed as English and changed the culture between US, India, Japan, and Brazil. Even though the same 50 personas were used, the networks changed.

The largest culture-driven homophily shift appeared in political affiliation. That means the role of politics in friendship formation changed the most across cultural contexts.

The topology also changed. The biggest structural change appeared in the largest connected component. In simple words, culture changed how connected or separated the whole network became.

So the result is: cultural framing affects both who connects with whom and how the overall graph is shaped.

# Research Question 2
Which demographic dimensions dominate tie formation under cultural and linguistic changes?

The main answer is political affiliation.

Across many experiments, political affiliation was the most frequent strongest homophily signal. That means the model often treated politics as one of the strongest reasons for people to become friends.

But there is an important detail: the generation method changes this.

In the global method, age often became the strongest signal. In local, sequential, and iterative, political affiliation was more often the strongest signal.

So the answer is not just "politics always dominates." The better answer is: political affiliation is the most stable dominant factor overall, but the generation method can shift which demographic signal becomes most important.

# Research Question 3
Do different LLM models produce consistent or divergent networks under identical conditions?

The answer is: they are not interchangeable.

I compared gpt-4.1, gpt-4.1-mini, and gpt-4.1-nano under the same conditions.

The most consistent pair was gpt-4.1 and gpt-4.1-mini. Their generated networks were usually the most similar.

The most different pair was gpt-4.1 and gpt-4.1-nano. That means the nano model did not simply behave like a smaller copy. It produced meaningfully different network structures.

So if someone asks whether newer GPT models dominate, I would say: the larger and mini models were more consistent with each other, but the nano model diverged more. The main finding is model choice matters.

# Research Question 4
When culture is held constant, does changing prompt language alter homophily and network topology?

The answer is yes.

Here, I fixed culture to the US and changed only the prompt language: English, Spanish, Hindi, and Japanese.

The networks still changed.

The largest language-driven homophily shift appeared in religion. That means changing the language affected how strongly the model connected people by religious similarity.

The largest topology shift again appeared in the largest connected component. So language changed not only small friendship choices, but the overall connected structure of the graph.

This is important because it shows prompt language itself can influence model behavior, even when the culture and personas stay fixed.

# Main Results
The strongest general result is that LLM-generated social networks are sensitive to prompting.

Political affiliation was usually the strongest demographic signal.

Culture changed both homophily and topology.

Prompt language changed the graph even when culture stayed fixed.

gpt-4.1 and gpt-4.1-mini behaved most similarly.

gpt-4.1-nano was more different from the larger models.

The global method produced the sparsest networks.

The iterative method produced the densest networks.

# How I Explain The Demo Video
This video shows the idea visually.

At first, we see 50 separate personas. They are not real people; they are synthetic agents with demographic attributes and interests.

Then connections start forming one by one. Each new line is a friendship choice generated by the model.

As more lines appear, we can see groups forming. Some people are tightly connected inside a group. Some people act like bridges between groups.

That is the core of the project: the model is not just generating individual people. It is generating social structure.

# Why This Matters
This matters because LLMs are increasingly used to simulate people, societies, users, voters, customers, and communities.

If a model generates a synthetic society, we need to understand what assumptions are built into that society.

Does it over-connect people with the same politics? Does it change behavior when the prompt language changes? Does it create different structures for different cultures? Does a smaller model create the same network as a larger one?

My project shows that these choices matter.

# Short Answers For Visitors
If someone asks "What is your project about?":
My project studies how LLMs generate friendship networks from synthetic personas, and how those networks change across culture, language, model size, and generation method.

If someone asks "What is the main result?":
The main result is that the generated networks are not neutral. They change depending on cultural context, prompt language, model choice, and method.

If someone asks "What is a persona?":
A persona is one synthetic person with demographics and interests, like age, gender, religion, political affiliation, race or ethnicity, and hobbies.

If someone asks "What is a network?":
A network is a graph where people are dots and friendships are lines.

If someone asks "What is homophily?":
Homophily means similar people connecting with similar people. In this project, political affiliation was often the strongest homophily signal.

If someone asks "What changed the most?":
Culture changed political homophily the most, and language changed religion homophily the most.

If someone asks "Which models were closest?":
gpt-4.1 and gpt-4.1-mini were the closest.

If someone asks "Which model was most different?":
gpt-4.1-nano was the most different from the larger models.

If someone asks "What method made the densest networks?":
The iterative method made the densest networks.

If someone asks "What method made the sparsest networks?":
The global method made the sparsest networks.

# Final Closing
The takeaway is that LLMs can generate social networks, but the generated society depends heavily on how we ask. Culture, language, model size, and method all shape the final network. So if we use LLMs for social simulation, we need to treat them as sensitive systems, not neutral generators.
""".strip()


def paragraphize(line: str, styles) -> tuple[Paragraph | Spacer | None, str | None]:
    if not line.strip():
        return Spacer(1, 0.08 * inch), None
    if line.startswith("# "):
        return Paragraph(line[2:].strip(), styles["Heading"]), "heading"
    if line.startswith("- "):
        return Paragraph("• " + line[2:].strip(), styles["Bullet"]), "bullet"
    return Paragraph(line.strip(), styles["Body"]), "body"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    TXT.write_text(NOTES + "\n", encoding="utf-8")

    base = getSampleStyleSheet()
    styles = {
        "Heading": ParagraphStyle(
            "Heading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#14324A"),
            spaceBefore=10,
            spaceAfter=5,
        ),
        "Body": ParagraphStyle(
            "Body",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=10.6,
            leading=14.4,
            textColor=colors.HexColor("#1B1B1B"),
            spaceAfter=4,
        ),
        "Bullet": ParagraphStyle(
            "Bullet",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=10.4,
            leading=13.8,
            leftIndent=18,
            firstLineIndent=-12,
            textColor=colors.HexColor("#1B1B1B"),
            spaceAfter=2,
        ),
    }

    doc = SimpleDocTemplate(
        str(PDF),
        pagesize=letter,
        rightMargin=0.62 * inch,
        leftMargin=0.62 * inch,
        topMargin=0.58 * inch,
        bottomMargin=0.58 * inch,
        title="Cross-Cultural and Linguistic Agentic Graph Simulation Framework Speaker Notes",
        author="UA Capstone",
    )

    story = []
    story.append(Paragraph("Speaker Notes", ParagraphStyle(
        "Title",
        parent=base["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#111111"),
        spaceAfter=6,
    )))
    story.append(Paragraph(
        "Cross-Cultural and Linguistic Agentic Graph Simulation Framework",
        ParagraphStyle(
            "Subtitle",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#4A4A4A"),
            spaceAfter=12,
        ),
    ))

    for line in NOTES.splitlines():
        item, _ = paragraphize(line, styles)
        if item is not None:
            story.append(item)

    doc.build(story)
    print(PDF)
    print(TXT)


if __name__ == "__main__":
    main()
